/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCheckBox: typeof import('./components/TheCheckBox.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHorizontalNavbar: typeof import('./components/TheHorizontalNavbar.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLoadingScreen: typeof import('./components/TheLoadingScreen.vue')['default']
    TheMenu: typeof import('./components/TheMenu.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheToast: typeof import('./components/TheToast/TheToast.vue')['default']
    TheTools: typeof import('./components/TheTools.vue')['default']
    ToastItem: typeof import('./components/TheToast/ToastItem.vue')['default']
  }
}
